#!/bin/bash

# fhdcapture - capturing picture from FullHD Capture webcam device
## Porpuse
# This script launches mplayer that is showing image from usb webcam.
# I am using it with ezcap device and SimpleScreenRecorder at second laptop.
# This way I am able to shot videos otherwise impossible to capture, for example,
# actions in bios setup or in bootloader.
#
# It is needed because vlc has ugly mess with colors while showing picture from ezcap.
# If you know how to fix this, feel free to contact me or open a new issue.

EZCAP_ENUM=`v4l2-ctl --list-devices | grep -A1 "FHD Capture" | tail -n1 | egrep -o '[0-9]'`
echo "\$EZCAP_ENUM = $EZCAP_ENUM"
mplayer -fs tv:// -tv driver=v4l2:device=/dev/video$EZCAP_ENUM:width=1920:height=1080:fps=30:outfmt=yuy2

## Usage
# $ fhdcapture
# Mplayer window will be automatically opened in fullscreen mode
# Record it with simplescreenrecorder or obs.
# To exit mplayer fullscreen mode and show title bar, press win + f11 (my own shortcut).
# I am launching fhdcapture in yakuake window, so to stop mplayer I again open it and press ctrl + c.
