#!/bin/bash

# fhdcapture - capturing picture from FullHD Capture webcam device
## Porpuse
# This script launches mplayer that is showing image from usb webcam.
# I am using it with ezcap devica and simplescreenrecorder at second laptop.
# This way I am able to shot videos otherwise impossible to capture, for example,
# actions in bios setup or in bootloader.
#
# It is needed because vlc has ugly mess with colors while showing picture from ezcap.
# If you know how to fix this, feel free to contact me or open a new issue.

echo "\$1 = $1"
mplayer tv:// -tv driver=v4l2:device=/dev/video$1:width=1920:height=1080:fps=30:outfmt=yuy2

## Usage
# $ fhdcapture <id of /dev/videoX device>
# Press win + f11 (my own shortcut) to expand window at full screen and hide title bar.
# Record it with simplescreenrecorder or obs.
