#!/usr/bin/env python3

# Author: Andrew Shark

# This script lists windows in kwin on wayland. It is useful, because wmctrl does not work on wayland.
# I read journalctl because printing in kwin script is currently broken. See https://bugs.kde.org/show_bug.cgi?id=445058

import subprocess
from datetime import datetime

datetime_now = datetime.now()

script = "/home/andrew/bin/list_windows.js"

reg_script_number = subprocess.run("dbus-send --print-reply --dest=org.kde.KWin \
                     /Scripting org.kde.kwin.Scripting.loadScript \
                     string:" + script + " | awk 'END {print $2}'",
                        capture_output=True, shell=True).stdout.decode().split("\n")[0]

subprocess.run("dbus-send --print-reply --dest=org.kde.KWin /" + reg_script_number + " org.kde.kwin.Script.run",
               shell=True)
subprocess.run("dbus-send --print-reply --dest=org.kde.KWin /" + reg_script_number + " org.kde.kwin.Script.stop",
               shell=True)  # unregister number

since = str(datetime_now)

msg = subprocess.run("journalctl _COMM=kwin_wayland -o cat --since \"" + since + "\"",
                     capture_output=True, shell=True).stdout.decode().rstrip().split("\n")
msg = [el.lstrip("js: ") for el in msg]
